# Generated by Django 5.1.4 on 2025-11-24 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', '-created'], name='courses_cou_subject_d0a713_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', '-created'], name='courses_cou_owner_i_be1a65_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title', '-created'], name='courses_cou_title_a0293f_idx'),
        ),
    ]
